# -*- coding: utf-8 -*-
"""Speech_to_Text_Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2c8Xng-kzfd8vRTTIi9q4xkbkB1o9gQ
"""

pip install transformers

from transformers import pipeline

import transformers
print(transformers.__version__)

import librosa

import torch

import IPython.display as display

from transformers import Wav2Vec2ForCTC ,Wav2Vec2Tokenizer

import numpy as np

tokenizer = Wav2Vec2Tokenizer.from_pretrained("facebook/wav2vec2-base-960h")
model = Wav2Vec2ForCTC.from_pretrained("facebook/wav2vec2-base-960h")

!pip install pysoundfile
!apt-get update && apt-get install ffmpeg -y
!pip install librosa audioread soundfile

audio , sampling_rate = librosa.load('/content/harvard.wav' , sr = 16000)

audio ,sampling_rate

display.Audio("/content/harvard.wav" ,autoplay = True)

input_values = tokenizer(audio ,return_tensors="pt").input_values
input_values

logits = model(input_values).logits
logits

predicated_ids = torch.argmax(logits , dim = -1)
predicated_ids

transcriptions = tokenizer.decode(predicated_ids[0])
transcriptions